def mostrar_menu():
    print("\nMenú de opciones:")
    print("1. Mostrar puntaje")
    print("2. Ordenar votos por nota promedio")
    print("3. Mostrar los peores 3 participantes")
    print("4. Mostrar participantes con promedio mayor al total")
    print("5. Mostrar cuál jurado tiene el peor promedio")
    print("6. Buscar participantes por la suma de sus tres notas")
    print("7. Definir el ganador")
    print("8. Salir\n")
